name: Deploy develop

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      env:
        GATSBY_PROJECT_PATH: "./new-website"
        GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY}}
      with:
        gatsby-arg: build
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: new-website
        path: new-website/public/
  deploy:
    name: Deploy to Firebase hosting
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: new-website
          path: new-website/public/
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}