name: Build Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      env:
        GATSBY_PROJECT_PATH: "./new-website"
        GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY}}
      with:
        gatsby-arg: build